title: Andre LeBlanc
email: hello@andremleblanc.com
description: Personal website of Andre LeBlanc.
url: "https://andremleblanc.com"
author: Andre LeBlanc

disqus:
  shortname: andreleblanc-me

tag_page_layout: tag_page
tag_page_dir: tag

markdown: kramdown
plugins:
  - jekyll-feed
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Capfile
  - README.md
  - config/
  - log/
