title: Andre LeBlanc
email: hello@andreleblanc.me
description: Personal website of Andre LeBlanc.
url: "https://andreleblanc.me"
author: Andre LeBlanc

disqus:
  shortname: andreleblanc-me

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: pretty

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
